### ISSUE TITLE
не работает указание source

### ISSUE THREAD

**Issue by ex0rcist** [drakmail/sms-uslugi-api#1]
Привет! Не работает указание source как имени отправителя - смс приходит с цифрового номера. Хотя отправка через обычный curl с указанием source работает нормально. Возможно проблема в faraday

**Comment by drakmail** [comment]
Привет! Возможно, это из-за того, что имя отправителя должно быть зарегистрировано в личном кабинете? Постараюсь проверить как можно быстрее.

**Comment by drakmail** [comment]
Сейчас проверил – дело в том, что надо использовать отправку через дорогой канал (use_alfasource должно быть 1). Вот пример:

``` ruby
@sms.send("teset message", PHONE_NUMBER, nil, SOURCE, 0, nil, 0, 1)
```

**Comment by ex0rcist** [comment]
Отправка curl'ом на адрес их апи без указания этого параметра приводит к использованию имени отправителя - может быть есть смысл тогда выставить этот флаг в единиицу по умолчанию?

**Comment by drakmail** [comment]
Тут есть проблема – если этот флаг поставить в единицу по умолчанию – то будет списываться в 3 раза примерно больше (1.65 вместо 0.35)

**Comment by ex0rcist** [comment]
Ну тогда добавь это в доки :) Вопрос закрыт, спасибо

**Comment by drakmail** [comment]
Да, думаю, это стоит описать в README.md. Спасибо за вопрос!
